service: aneventstoat

provider:
  name: aws
  runtime: python3.8
  region: us-east-1

custom:
  pythonRequirements:
    dockerizePip: true

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  an_endpoint:
    handler: src.functions.an_endpoint.handler
    events:
      - http:
          path: an_endpoint
          method: post
    environment:
      ACTION_NETWORK_API_KEY: ${ssm:/action-network-api-key~true}
      AIRTABLE_API_KEY: ${ssm:/airtable-api-key~true}
  sync_events:
    handler: src.functions.sync_events.handler
    events:
      - schedule: rate(30 minutes)
    environment:
      ACTION_NETWORK_API_KEY: ${ssm:/action-network-api-key~true}
      AIRTABLE_API_KEY: ${ssm:/airtable-api-key~true}

plugins:
  - serverless-python-requirements
