service: aneventstoat

provider:
  name: aws
  runtime: python3.8
  region: us-east-1

custom:
  pythonRequirements:
    dockerizePip: true

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  hello:
    handler: src.handlers.hello_handler
    events:
      - http:
          path: joke
          method: get
    environment:
      ACTION_NETWORK_API_KEY: ${ssm:/action-network-api-key~true}
  an_endpoint:
    handler: src.handlers.an_endpoint_handler
    events:
      - http:
          path: an_endpoint
          method: post
    environment:
      ACTION_NETWORK_API_KEY: ${ssm:/action-network-api-key~true}

plugins:
  - serverless-python-requirements
