service: aneventstoat

provider:
  name: aws
  runtime: python3.8
  region: us-east-1

custom:
  pythonRequirements:
    dockerizePip: true

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: joke
          method: get
    environment:
      variable2: value2

plugins:
  - serverless-python-requirements
